shelcia/mocker

frontend/src/pages/dashboard/Collection.jsx, frontend/src/pages/dashboard/components/ResourceModal.jsx
Added Loader for JSON creation fixing issue #14 .
=> added loader for JSON creation

frontend/src/pages/dashboard/Dashboard.jsx
The project color changes on hover
=> Project Clickable

frontend/src/pages/auth/Login.jsx
Validation on Login page is now working properly
Fixes #17
=> [Add] :- Validation on Login Page

frontend/src/pages/auth/Login.jsx
There is no loading after calling login api so i added loader in which this loader will start when we click on login and finish after we get the response.
=> [ADDED] : Loading added in login page

frontend/src/pages/dashboard/Dashboard.jsx
After creating a new project, it automatically added in the list of project without refreshing the page
Fixed #34 issue produced after #27
=> [Bug fix]: Refresh new project list

frontend/src/pages/auth/Signup.jsx
There is no loading after calling Sign up api so i added loader in which this loader will start when we click on sign up and finish after we get the response.
issue fixed #20
=> [ADDED] : Loading added in Sign up page

frontend/src/pages/dashboard/components/EndpointModal.jsx
There is no option to copy endpoint So i have added button to copy endpoint as proper URLS.
Issue Fixed :- Copy endpoint as proper URLs #24
=> [Update] Copy endpoint as proper URLs

frontend/src/components/Custom404.jsx, frontend/src/routes.jsx
Issue Fixed 👍🏻  Need 404 page #1
=> [ADDED] 404 Not Found Page Added

backend/.env.sample, frontend/src/pages/dashboard/components/CloneModal.jsx, frontend/src/pages/dashboard/components/EditResourceModal.jsx, frontend/src/pages/dashboard/components/ResourceModal.jsx
Fields are grouped together according to the resource type in the dropdown
resolves #23 issue
=> [UPDATE] : Group fields in adding resource from dropdown

backend/.env.sample, backend/index.js, backend/middleware/authenticate.js, backend/models/User.js, backend/package.json, backend/routes/auth/auth.js, backend/routes/service/service.js, backend/routes/service/verify.js, frontend/src/layout/DashboardLayout.jsx, frontend/src/pages/auth/EmailVerify.jsx, frontend/src/pages/auth/Login.jsx, frontend/src/routes.jsx
Before deploying please set environment variable as shown [here](https://github.com/shelcia/mocker/pull/44/commits/6d71494b1f1c7aeb65e9915290c3399ca6e82ab7#diff-0e320819a20d54d985ec682f82c0e0be462b12a8a26e57a339cb68947fcfeeb6R5-R6)
```
EMAIL_ID = "email_id"
EMAIL_PWD = "password"
```
I have used gmail as a smtp server.. Password can be generated from security section and it requires 2 step verification
=> [ADDED]: Email verification

frontend/src/layout/DashboardLayout.jsx, frontend/src/pages/auth/Login.jsx, frontend/src/services/api.js, frontend/src/services/models/serviceModel.js, frontend/src/services/utilities/provider.js
PR #44 has an issue that needs a full page refresh to show up the "verify email" button after first login. So I fixed the issue in this PR
=> [BUG FIX]: "Verify email" button needs refresh to show

backend/routes/resource/resource.js, frontend/src/pages/dashboard/components/ResourceModal.jsx
Resolves #22 
Added all the fakerjs random generator
=> [ADDED]: All random function generator

frontend/src/pages/auth/Login.jsx, frontend/src/pages/auth/Signup.jsx
=> Login and SignUp Box Size Problem Solved

backend/routes/resource/resource.js, frontend/src/pages/dashboard/components/CloneModal.jsx, frontend/src/pages/dashboard/components/EditResourceModal.jsx, frontend/src/pages/dashboard/components/ResourceModal.jsx, frontend/src/pages/dashboard/components/SchemaOption.jsx
While choosing field or type of data, one can also put various criteria for the data to be generated.
Option can be put during resource edit and cloning resource as well.
=> [Feature]: Various option to include while generating fakerjs data

backend/routes/auth/auth.js, frontend/src/pages/auth/ForgotPassword.jsx, frontend/src/pages/auth/Login.jsx, frontend/src/routes.jsx
=> [ADDED]: Forgot password

frontend/src/pages/dashboard/components/CommonResourceModal.jsx, frontend/src/pages/dashboard/components/SchemaOptionModal.jsx
=> [BUG FIX AND ENHANCE]: Option menu retain its previous data

frontend/src/pages/dashboard/components/CommonResourceModal.jsx
Issue #59 resolved by me on #66, has a bug that does not validate negative number on number of object so I fixed in this PR.
=> [BUG FIX]: Validate negative number.

backend/routes/resource/resource.js, frontend/src/pages/dashboard/components/CommonResourceModal.jsx, frontend/src/pages/dashboard/components/SchemaOptionModal.jsx
=> [ADDED]: Datatype module added with all the options

frontend/src/pages/dashboard/components/CloneModal.jsx, frontend/src/pages/dashboard/components/EditResourceModal.jsx
[MOCKER_issue-77.webm](https://user-images.githubusercontent.com/56883128/209667598-a5af1733-ae1f-42c3-aa0d-ec19a1be3abd.webm)
=> [ADDED]: Loader on resource update and cloning data

backend/routes/user/user.js
=> Check for invalid objectId when sending a delete request

backend/routes/auth/auth.js, backend/routes/service/service.js
Tested all functions affected by the changes.
=> [FIX]: Codeql nosql injection alert

backend/index.js, backend/package.json
Added request rate limit to backend API to improve system performance and stability
=> [FIX]: Codeql missing rate limiting alert

backend/routes/user/user.js
=> Added check for invalid resourceId

backend/routes/project/project.js, frontend/src/pages/dashboard/Dashboard.jsx
Added an option to rename group
Here is a video I have added
[MOCKER_rename.webm](https://user-images.githubusercontent.com/56883128/209980581-3650ff67-fcd2-46e1-86c3-9edc4951f957.webm)
=> [ADDED]: Group rename

backend/routes/resource/resource.js, frontend/src/pages/dashboard/Collection.jsx, frontend/src/services/models/resourceModal.js, frontend/src/services/utilities/core.js, frontend/src/services/utilities/provider.js
[MOCKER_select_delete.webm](https://user-images.githubusercontent.com/56883128/210125864-4c3e44f1-ae57-4426-adde-c54ea7345601.webm)
=> [ADDED]: Delete multiple resources at once

frontend/documentation/color.md, frontend/documentation/commerce.md, frontend/documentation/datatype.md, frontend/documentation/date.md, frontend/documentation/finance.md, frontend/documentation/image.md, frontend/documentation/internet.md, frontend/documentation/lorem.md, frontend/documentation/music.md, frontend/documentation/name.md, frontend/documentation/random.md, frontend/documentation/science.md
=> Documentation

backend/routes/project/project.js, frontend/src/pages/dashboard/Dashboard.jsx, frontend/src/pages/dashboard/components/ConfirmDelProjectModal.jsx, frontend/src/services/models/projectModel.js
[MOCKER_multiple_project_delete.webm](https://user-images.githubusercontent.com/56883128/210162141-b6374da5-6f03-4184-8a17-0d7ad05dc0b1.webm)
=> [ADDED]: Delete multiple project at once

frontend/src/pages/dashboard/Collection.jsx
Here is a video I have added showing different dimension.
[MOCKER_alignment_issue.webm](https://user-images.githubusercontent.com/56883128/210168475-7eaec4bb-f60a-4132-90f5-e02a7e863c64.webm)
=> [Fix]: Fixed resources list alignment

backend/routes/project/project.js
=> Delete all the associated resources when its project is deleted

backend/routes/resource/resource.js, docs/docs/models/vehicle.md, frontend/src/pages/dashboard/components/CommonResourceModal.jsx
=> [ADDED]: vehicle module

backend/routes/resource/resource.js, docs/docs/models/address.md, docs/docs/models/hacker.md, docs/docs/models/system.md, frontend/src/pages/dashboard/components/CommonResourceModal.jsx, frontend/src/pages/dashboard/components/SchemaOptionModal.jsx
Here I have added screenshot of each module:
=> [ADDED]: Address, System and hacker module with doc and options

backend/routes/resource/resource.js, docs/docs/models/database.md, frontend/src/pages/dashboard/components/CommonResourceModal.jsx
=> [ADDED]: database module with doc

frontend/src/pages/dashboard/Collection.jsx
I have added a video showing the link is clickable only when the cursor is above the text
[MOCKER_fix_link_issue.webm](https://user-images.githubusercontent.com/56883128/211033154-df9ddbf2-6d6e-444d-a1c4-d42f0ee76e6f.webm)
=> Improved postman documentation link

README.md
Hello @shelcia 
Referring the Issue #127
Kindly check this out and merge it asap with IWOC labels
- Contributors details
- Project admin details
- Add the contributing line with a guideline link so that everyone motivates by that.
- Center heading for more attractive
- the footer part in the readme file
=> 🧑‍💻  Updated README file

backend/middleware/authenticate.js
Eliminating unnecessary promises and utilizing the **jwt.verify** function with a callback. If an error occurs, return 'something wrong'; otherwise, proceed to the next middleware with the payload attached to **req.body**.
=> Streamlining unnecessary promise, async, and await syntax.

backend/routes/auth/auth.js
added expiry date to json web token.
=> Fixes issue #140

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/doc_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/other.yml, .github/ISSUE_TEMPLATE/style.yml, .github/PULL_REQUEST_TEMPLATE.md
=> feat: templates added
